journal/administrator/urls.py
from.views import *
from django.urls import path

urlpatterns =[
    path('group/', group, name = 'group'),
    path('add_group/', add_group, name = 'add_group'),
    path('edit_group/<int:pk>', edit_group, name = 'edit_group'),
    path('delete_group/<int:pk>', delete_group, name = 'delete_group'),
    path('coaches/', coaches, name = 'coaches'),
    path('students/', students, name = 'students'),
    path('coach/<int:pk>', coach, name = 'coach'),
    path('save_coach_groups/<int:pk>', save_coach_groups, name = 'save_coach_groups'),
    path('student/<int:pk>', student, name = 'student'),
    path('save_student_group/<int:pk>', save_student_group, name = 'save_student_group'),
    path('delete_student_group/<int:pk>', delete_student_group, name = 'delete_student_group'),
    path('get_students_list/<int:pk>', get_students_list, name = 'get_students_list'),
    path('periods/', periods, name = 'periods'),
    path('add_period/', add_period, name = 'add_period'),
    path('get_period/<int:pk>/',get_period, name='get_period'),
    path('edit_period/<int:pk>/', edit_period, name = 'edit_period'),
    path('delete_period/<int:pk>', delete_period, name = 'delete_period'),
    path('halls/', halls, name = 'halls'),
    path('add_hall/', add_hall, name = 'add_hall'),
    path('get_hall/<int:pk>/', get_hall, name = 'get_hall'),
    path('edit_hall/<int:pk>/', edit_hall, name = 'edit_hall'),
    path('delete_hall/<int:pk>/', delete_hall, name = 'delete_hall'),
    path('schedule/', schedule, name = 'schedule'),
    path('add_schedule/', add_schedule, name = 'add_schedule'),
    path('save_schedule/', save_schedule, name = 'save_schedule'),# Разделение функции охранения на две части 1.Открытие страницы сохранения 2.Само сохранение
]

journal/journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'),namespace = 'users')),
    path('student/', include(('student.urls', 'student'),namespace = 'student')),
    path('teacher/', include(('teacher.urls', 'teacher'), namespace = 'teacher')),
    path('administrator/', include(('administrator.urls', 'administrator'), namespace = 'administrator'))
    
     
]
urlpatterns += staticfiles_urlpatterns()

journal/student/urls.py
from.views import *
from django.urls import path

urlpatterns = [
        path('schedule/', schedule, name ='schedule'),
        
]

journal/users/urls.py
from.views import *
from django.urls import path



urlpatterns = [
    path('log_in/', log_in, name = 'log_in'),
    path('log_out/', log_out, name = 'log_out'),
    path('profile/', profile, name = 'profile'),
    path('profile/update-avatar/', update_avatar, name='update_avatar'), 
    path('profile/edit_profile/', edit_profile, name = 'edit_profile'),
    path('profile/change_password', change_password, name = 'change_password'),
    path('profile/profile_update/', profile_update, name = 'profile_update'),
    path('create_user/', register, name='create_user'),
    path('edit_user/<int:pk>', edit_user, name = 'edit_user'),
    path('delete_user/<int:pk>', delete_user, name = 'delete_user'),
    path('patch_user/<int:pk>', patch_user, name = 'patch_user'),# patch - не большое обновление данных пользователя
    path('index/', users, name = 'users'),
    path('change_password/<int:pk>', change_password, name = 'change_password'),
]

journal/student/models.py
from django.db import models



# Create your models here.

journal/administrator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import GroupForm, Group, CustomUser, PeriodForm, HallForm
from django.http import HttpResponse, JsonResponse
import json
from django.db.models import Count, Q
from .models import *
from users.forms import RegisterForm


def group(request):
    groups = Group.objects.all()
    return render(request, "group.html", {"groups": groups})


def add_group(request):
    form = GroupForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("administrator:group")
    return render(request, "add_group.html", {"form": form})


def edit_group(request, pk):
    group_data = Group.objects.get(pk=pk)
    form = GroupForm(
        request.POST or None, instance=group_data
    )  # Заполняем форму и передаем ее в шаблон
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("administrator:group")
    return render(request, "add_group.html", {"form": form})


def delete_group(request, pk):
    group_data = Group.objects.get(pk=pk)
    if request.method == "POST":
        group_data.delete()
    return HttpResponse()


def coaches(request):
    coaches = CustomUser.objects.filter(role="Тренер").annotate(
        student_count=Count("coach_groups__group_students")
    )

    return render(request, "coaches.html", {"coaches": coaches})


def students(request):
    student_list = CustomUser.objects.filter(role="Спортсмен")

    return render(request, "students.html", {"students": student_list})


def coach(request, pk):
    coach_data = get_object_or_404(CustomUser, pk=pk)

    # Получаем список, групп тренера в виде словарей с id и именем группы.
    coach_groups = list(coach_data.coach_groups.values("id", "group_name"))
    all_groups = list(Group.objects.values("id", "group_name"))

    return JsonResponse(
        {
            "coach_id": coach_data.id,
            "coach_groups": coach_groups,
            "all_groups": all_groups,
            "coach_name": coach_data.get_full_name(),
        }
    )


def save_coach_groups(request, pk):
    # Находим трнера
    coach = get_object_or_404(CustomUser, pk=pk)

    # json строку превращаем в python словарь, чтобы
    # можно было достать информацию
    data = json.loads(request.body)

    # Достаем из словаря все id группы
    groups_id = data.get("groups")

    # Убираем тренера у всех его групп
    Group.objects.filter(coach=coach).update(coach=None)

    # Находим все выбранные группы и назначаем им тренера
    Group.objects.filter(id__in=groups_id).update(coach=coach)

    # Передаем команду, действие выполнено успешно
    return JsonResponse({"status": "ok"})


# Отвечает за открытие модального окна и вывода информации и показ группы к которой студент прикреплен
def student(request, pk):
    student_data = get_object_or_404(CustomUser, pk=pk)

    try:
        student_group = student_data.current_groups
        current_group = [
            {"id": student_group.group.id, "group_name": student_group.group.group_name}
        ]
    except StudentGroup.DoesNotExist:
        current_group = []

    all_groups = list(Group.objects.values("id", "group_name"))

    return JsonResponse(
        {
            "student_id": student_data.id,
            "current_group": current_group,
            "all_groups": all_groups,
        }
    )


def save_student_group(request, pk):

    student = get_object_or_404(CustomUser, pk=pk)

    data = json.loads(request.body)

    group_id = data.get("group")[0]

    student_group = StudentGroup.objects.filter(student=student).exists()
    if student_group:
        StudentGroup.objects.filter(student=student).update(group=group_id)
    else:
        group = get_object_or_404(Group, pk=group_id)
        StudentGroup.objects.create(student=student, group=group)

    return JsonResponse({"status": "ok"})


def delete_student_group(request, pk):

    student_group = get_object_or_404(StudentGroup, pk=pk)

    if request.method == "POST":
        student_group.delete()

    return JsonResponse({"status": "ok"})


def get_students_list(request, pk):
    group = Group.objects.get(pk=pk)

    student_list = group.group_students.all()

    response = []

    for student_group in student_list:
        response.append(
            {
                "id": student_group.student.id,
                "full_name": student_group.student.get_full_name(),
            }
        )

    response = sorted(
        response, key=lambda x: x["full_name"]
    )  # Сортировка списа студентов по имени

    return JsonResponse({"students": response, "group_name": group.group_name})


def periods(request):
    form = PeriodForm()
    periods = SchedulePeriod.objects.order_by(
        "date_start"
    )  # по дате начала по возрастанию
    return render(request, "periods.html", {"form": form, "periods": periods})


def add_period(request):
    form = PeriodForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        period = form.save()
        return JsonResponse(
            {
                "success": True,
                "period": {
                    "id": period.id,
                    "name": period.name,
                    "date_start": period.date_start.strftime("%Y-%m-%d"),
                    "date_end": period.date_end.strftime("%Y-%m-%d"),
                },
            }
        )

    return JsonResponse({"success": False, "errors": form.errors}, status=400)


def delete_period(request, pk):
    data_period = SchedulePeriod.objects.get(pk=pk)
    if request.method == "POST":
        data_period.delete()
    return HttpResponse()


# Берем период который будет редактироваться
def get_period(request, pk):
    period = get_object_or_404(SchedulePeriod, pk=pk)

    return JsonResponse(
        {
            "id": period.id,
            "name": period.name,
            "date_start": period.date_start.strftime("%Y-%m-%d"),
            "date_end": period.date_end.strftime("%Y-%m-%d"),
        }
    )


def edit_period(request, pk):
    period_data = SchedulePeriod.objects.get(pk=pk)
    form = PeriodForm(request.POST or None, instance=period_data)

    if request.method == "POST" and form.is_valid():
        period = form.save()
        return JsonResponse(
            {
                "success": True,
                "period": {
                    "id": period.id,
                    "name": period.name,
                    "date_start": period.date_start.strftime("%Y-%m-%d"),
                    "date_end": period.date_end.strftime("%Y-%m-%d"),
                },
            }
        )
    return JsonResponse({"success": False, "errors": form.errors}, status=400)


# CRUD - зал
def halls(request):
    form = HallForm()
    halls = Hall.objects.order_by("hall_name")  # по дате начала по возрастанию
    return render(request, "halls.html", {"form": form, "halls": halls})


def add_hall(request):
    form = HallForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        hall = form.save()
        return JsonResponse(
            {
                "success": True,
                "hall": {
                    "id": hall.id,
                    "hall_name": hall.hall_name,
                    "training_type": hall.training_type.name,
                },
            }
        )

    return JsonResponse({"success": False, "errors": form.errors}, status=400)


def delete_hall(request, pk):
    data_hall = Hall.objects.get(pk=pk)
    if request.method == "POST":
        data_hall.delete()
    return HttpResponse()


# Берем зал который будет редактироваться
def get_hall(request, pk):
    hall = get_object_or_404(Hall, pk=pk)

    return JsonResponse(
        {
            "id": hall.id,
            "hall_name": hall.hall_name,
            "training_type": hall.training_type.id,
        }
    )


def edit_hall(request, pk):
    hall_data = Hall.objects.get(pk=pk)
    form = HallForm(request.POST or None, instance=hall_data)

    if request.method == "POST" and form.is_valid():
        hall = form.save()
        return JsonResponse(
            {
                "success": True,
                "hall": {
                    "id": hall.id,
                    "hall_name": hall.hall_name,
                    "training_type": hall.training_type.name,
                },
            }
        )
    return JsonResponse({"success": False, "errors": form.errors}, status=400)


# Расписание


def schedule(request):
    # Передавать всех тренеров, все залы, все группы, все периоды
    return render(request, "schedule.html")


def add_schedule(request):
    coaches = CustomUser.objects.filter(role="Тренер")
    all_groups = Group.objects.all()
    halls = Hall.objects.all()
    periods = SchedulePeriod.objects.all()
    weekdays = WeekDay.objects.all()

    return render(
        request,
        "add_schedule.html",
        {
            "coaches": coaches,
            "all_groups": all_groups,
            "halls": halls,
            "periods": periods,
            "weekdays": weekdays,
        },
    )

# Функция сохранения созданного расписания

def save_schedule(request):
    if request.method == 'POST':
        coach = request.POST.get('coach')
        group = request.POST.get('group')
        hall = request.POST.get('hall')
        period = request.POST.get('period')
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        weekdays = request.POST.get('weekdays')
        schedule = Schedule.objects.create(
            coach_id = coach,
            group_id = group,
            hall_id = hall,
            period_id = period,
            start_time = start_time,
            end_time = end_time,

        )
        schedule.weekdays.set(weekdays)
        return redirect('administrator:schedule')

# Create your views here.

journal/student/views.py
from django.shortcuts import render

def schedule(request):
    return render(request, 'schedule.html')

# Create your views here.

journal/users/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from.models import *
import json


def register(request):
    if not request.user.is_superuser:
        return HttpResponse('Извиниет у Вас нет прав для выполнения этого действия')
    
    form = RegisterForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        user = form.save(commit=False)  # не сохраняем сразу
        user.username = form.cleaned_data["email"]  # подставляем email
        user.set_password ('12345678')
        user.save()  # теперь сохраняем
        return redirect("users:users")  # переход на страницу пользователей

    return render(request, "register.html", {"form": form})


def log_in(request):

    form = LoginForm(data=request.POST or None)

    if form.is_valid():
        user = form.get_user()
        login(request, user)

        return redirect("student:schedule")

    return render(request, "log_in.html", {"form": form})


def log_out(request):
    logout(request)
    return redirect("users:log_in")


@login_required(login_url='/users/log_in')  # нужно импортировать login_required
def profile(request):
    return render(request, "profile.html", {"user_obj": request.user})


@login_required(login_url='/users/log_in')
def update_avatar(request):
    if request.method == "POST":
        avatar = request.FILES.get("avatar")
        if avatar:
            request.user.profile.image = avatar
            request.user.profile.save()
        return redirect("users:profile")

    return redirect("users:profile")


@login_required(login_url='/users/log_in')
def edit_profile(request):
    return render(request, "edit_profile.html")


@login_required(login_url='/users/log_in')
def change_password(request):
    return render(request, "change_password.html")


@login_required(login_url='/users/log_in')
def profile_update(request):
    return render(request, "profile_update.html")

def users(request):
    users = CustomUser.objects.filter(is_superuser = False)

    return render(request, 'users.html', {'users':users})

@login_required(login_url='/users/log_in')
def edit_user(request, pk):
    user = CustomUser.objects.get(pk=pk)
    form = RegisterForm(request.POST or None, instance = user)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('users:users')
    return render(request, 'register.html', {'form':form})

@login_required(login_url='/users/log_in')
def delete_user(request, pk):
    user_data = CustomUser.objects.get(pk=pk)
    if request.method == 'POST':
        user_data.delete()
    return redirect('users:users')

@login_required(login_url='/users/log_in')
def patch_user(request, pk):
    user = CustomUser.objects.get(pk=pk)
    user.is_active = not user.is_active
    user.save()
    
    return redirect('users:users')

@login_required(login_url='/users/log_in')
def change_password(request, pk):
    data = json.loads(request.body)
    password1 = data.get('password1')
    password2 = data.get('password2')

    if len (password1) < 8:
        return JsonResponse('Пароль слишком короткий')
    
    if password1 != password2:
        return JsonResponse('Пароли не совпадают')
    
    user = request.user
    user.set_password(password1)
    user.save()
    update_session_auth_hash(request, user)

    return HttpResponse('Смена пароля')

journal/administrator/templates/add_schedule.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}

<body class="d-flex justify-content-center" style="height: 100vh;">
    <form action="{% url 'administrator:save_schedule' %}" method="post" class="p-4 border rounded" style="width: 600px; min-width: 300px;">
        {% csrf_token %}
        <div class="mb-3">
            <label for="coachSelect" class="form-label">Выберите тренера</label>
            <select name="coach" required class="form-select" id="coachSelect">
                <option value="" selected disabled>Не выбрано</option>
                {% for coach in coaches %}
                <option value="{{coach.id}}">{{ coach.get_full_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="groupSelect" class="form-label">Выберите группу</label>
            <select name="group" required class="form-select" id="groupSelect">
                <option value="" selected disabled>Не выбрано</option>
                {% for group in all_groups %}
                <option value="{{group.id}}">{{ group.group_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="hallSelect" class="form-label">Выберите зал</label>
            <select name="hall" required class="form-select" id="hallSelect">
                <option value="" selected disabled>Не выбрано</option>
                {% for hall in halls %}
                <option value="{{hall.id}}">{{ hall.hall_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="periodSelect" class="form-label">Выберите период</label>
            <select name="period" required class="form-select" id="periodSelect">
                <option value="" selected disabled>Не выбрано</option>
                {% for period in periods %}
                <option value="{{period.id}}">{{ period.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Выберите дни недели</label>
            {% for weekday in weekdays %}
             <div class="form-check">
                <input name="weekdays" class="form-check-input" type="checkbox" id="day-{{weekday.id}}" value="{{weekday.id}}">
                <label class="form-check-label" for="day-{{weekday.id}}">
                    {{weekday.name}}
                </label>
            </div>

            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="weekdaysSelect" class="form-label">Выберите время тренировки</label>
            <br>
            <input name="start_time" required type="time" class="form-control-sm"> - <input name="end_time" required type="time" class="form-control-sm">
        </div>
        <div class="d-flex justify-content-center gap-1">
            <button type="submit" class="btn btn-primary w-100">Создать</button>
            <a href="{% url 'administrator:schedule' %}" class="btn btn-secondary w-100">Отменить</a>
        </div>


        {% if form.non_field_errors %}
        <div class="text-danger mt-3">
            {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
    </form>
</body>
<script>
    // Делаем выбор дня недели обязательным полем 

    document.querySelector('form').addEventListener('submit', function(){
        let inputs = document.querySelectorAll('input[name="weekdays"]:checked')
        if (inputs.length === 0){
            alert('Выберите хотябы один день') 
        }
        
    })
</script>
{% endblock %}

journal/administrator/templates/users.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<div class="container py-4">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="mb-0">Пользователи</h2>
        <a href="{% url 'users:create_user' %}" class="btn btn-primary">
            <i class="bi bi-people me-2"></i>
            Добавить пользователя
        </a>
    </div>

    <!-- <div class="table-responsive"> -->
    <table class="table table-striped table-hover align-middle">
        <thead class="table-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Полное имя</th>
                <th scope="col" class="text-end">Дата рождения</th>
                <th scope="col" class="text-center">Почта</th>
                <th scope="col" class="text-end">Номер телефона</th>
                <th scope="col" class="text-end">Роль</th>
                <th scope="col" class="text-end">Статус</th>
                <th scope="col" class="text-end">Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td class="text-center">{{ user.id }}</td>
                <td class="text-center">{{ user.get_full_name|default:"-" }}</td>
                <td class="text-center">{{ user.birth_date|default:"Не указано" }}</td>
                <td class="text-center">{{ user.email|default:"-" }}</td>
                <td class="text-center">{{ user.phone_number|default:"-" }}</td>
                <td class="text-center">
                    {% if user.role == 'Администратор' %}
                    <span class="badge bg-primary"> {{ user.role|default:"-" }}</span>
                    {% elif user.role == 'Тренер' %}
                    <span class="badge bg-info"> {{ user.role|default:"-" }}</span>
                    {% elif user.role == 'Спортсмен' %}
                    <span class="badge bg-secondary"> {{ user.role|default:"-" }}</span>
                    {% endif %}
                </td>
                <td class="text-center">
                    {% if user.is_active %}
                    <span class="badge bg-success">Активен</span>
                    {% else %}
                    <span class="badge bg-danger">Не активен</span>
                    {% endif %}
                </td>
                <td class="text-end">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                        <!-- Выпадающй список -->
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:edit_user' user.pk %}">
                                    <i class="bi bi-pencil me-2"></i>Редактировать
                                </a>
                            </li>
                            <li>
                                <button class="dropdown-item delete-user-btn" type="button" data-bs-toggle="modal"
                                    data-bs-target="#deleteUserModal" id="{{ user.pk }}">
                                    <i class="bi bi-trash me-2"></i>Удалить
                                </button>
                            </li>
                            <li>
                                <button class="dropdown-item change-password-btn" type="button" data-bs-toggle="modal"
                                    data-bs-target="#changePasswordModal" id="{{ user.pk }}">
                                    <i class="bi bi-lock me-2"></i>Сменить пароль
                                </button>
                            </li>
                            <li>
                                <a href="{% url 'users:patch_user' user.pk %}" class="dropdown-item activate-user-btn"
                                    type="button" data-user-id="{{ user.pk }}">
                                    {% if user.is_active %}
                                    <i class="bi bi-x-circle me-2"></i>Деактивировать
                                    {% else %}
                                    <i class="bi bi-check-circle me-2"></i>Активировать
                                    {% endif %}

                                </a>
                            </li>
                        </ul>
                    </div>
                </td>

            </tr>
            {% endfor %}
        </tbody>

    </table>
    <!-- </div> -->
    <!-- Модальное окно для смены пароля пользователя -->
    <div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="changePasswordModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changePasswordModalLabel">Смена пароля</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="changePasswordForm" method="post" style="display: inline;">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="password1" class="form-label">Новый пароль</label>
                            <input type="password" class="form-control" id="password1">
                        </div>
                        <div class="mb-3">
                            <label for="password2" class="form-label">Подтвердите пароль</label>
                            <input type="password" class="form-control" id="password2">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>

                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Сохранить</button>

                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Модальное окно удаления пользователя -->
    <div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteUserModalLabel">Удалить пользователя?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Вы уверены, что хотите удалить пользователя?
                    <div class="alert alert-warning mt-2">
                        Все данные связанные с этим пользователем будут удалены!
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    <form id="deleteUserForm" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function () {

        // открытие модалки удаления
        let id;
        let deleteButtons = document.querySelectorAll('.delete-user-btn')
        let changePasswordBtns = document.querySelectorAll('.change-password-btn')

        deleteButtons.forEach(function (btn) {
            btn.onclick = function () {
                id = btn.id
            }
        })

        changePasswordBtns.forEach(function (btn) {
            btn.onclick = function () {
                id = btn.id
            }
        })


        //  удаление пользователя

        let userDeleteForm = document.querySelector('#deleteUserForm')


        userDeleteForm.onsubmit = function (event) {
            event.preventDefault()
            console.log(id);

            fetch('/users/delete_user/' + id, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')// getCookie - вернет тот параметр который мы запросим, в данном случае она возвращает csrf - токен
                },

            })
                .then(response => location.reload())  // promise - действия которые выполняются раз за разом.
                .catch(error => console.log(error))
        }

        let changePasswordForm = document.querySelector('#changePasswordForm')

        changePasswordForm.onsubmit = function (event) {
            let password1 = document.querySelector('#password1').value
            let password2 = document.querySelector('#password2').value
            event.preventDefault()

            if (password1.length < 8) {
                alert('Пароль слишком короткий')
                return
            }

            if (password1 != password2) {
                alert('Пароли не совпадают')
                return
            }


            fetch('/users/change_password/' + id, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')// getCookie - вернет тот параметр который мы запросим, в данном случае она возвращает csrf - токен
                },
                body: JSON.stringify({
                    password1, password2
                })
            })
                .then(response => location.reload())
                .catch(error => console.log(error))
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let cookie of cookies) {
                    cookie = cookie.trim();
                    if (cookie.startsWith(name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }


            return cookieValue;
        }
    });
</script>
{% endblock %}