journal/administrator/urls.py
from.views import *
from django.urls import path

urlpatterns =[
    path('group/', group, name = 'group'),
    path('add_group/', add_group, name = 'add_group'),
    path('edit_group/<int:pk>', edit_group, name = 'edit_group'),
    path('delete_group/<int:pk>', delete_group, name = 'delete_group'),
    path('coaches/', coaches, name = 'coaches'),
    path('students/', students, name = 'students'),
    path('coach/<int:pk>', coach, name = 'coach'),
    path('save_coach_groups/<int:pk>', save_coach_groups, name = 'save_coach_groups'),
    path('student/<int:pk>', student, name = 'student'),
    path('save_student_group/<int:pk>', save_student_group, name = 'save_student_group'),
    path('delete_student_group/<int:pk>', delete_student_group, name = 'delete_student_group'),
    path('get_students_list/<int:pk>', get_students_list, name = 'get_students_list'),
    path('periods/', periods, name = 'periods'),
    path('add_period/', add_period, name = 'add_period'),
    path('get_period/<int:pk>/',get_period, name='get_period'),
    path('edit_period/<int:pk>/', edit_period, name = 'edit_period'),
    path('delete_period/<int:pk>', delete_period, name = 'delete_period'),
    path('halls/', halls, name = 'halls'),
    path('add_hall/', add_hall, name = 'add_hall'),
    path('get_hall/<int:pk>/', get_hall, name = 'get_hall'),
    path('edit_hall/<int:pk>/', edit_hall, name = 'edit_hall'),
    path('delete_hall/<int:pk>/', delete_hall, name = 'delete_hall'),
    path('schedule/', schedule, name = 'schedule'),
    path('add_schedule/', add_schedule, name = 'add_schedule'),
    path('save_schedule/', save_schedule, name = 'save_schedule'),# Разделение функции охранения на две части 1.Открытие страницы сохранения 2.Само сохранение
]

journal/journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'),namespace = 'users')),
    path('student/', include(('student.urls', 'student'),namespace = 'student')),
    path('teacher/', include(('teacher.urls', 'teacher'), namespace = 'teacher')),
    path('administrator/', include(('administrator.urls', 'administrator'), namespace = 'administrator'))
    
     
]
urlpatterns += staticfiles_urlpatterns()

journal/student/urls.py
from.views import *
from django.urls import path

urlpatterns = [
        path('schedule/', schedule, name ='schedule'),
        
]

journal/users/urls.py
from.views import *
from django.urls import path



urlpatterns = [
    path('log_in/', log_in, name = 'log_in'),
    path('log_out/', log_out, name = 'log_out'),
    path('profile/', profile, name = 'profile'),
    path('profile/update-avatar/', update_avatar, name='update_avatar'), 
    path('profile/edit_profile/', edit_profile, name = 'edit_profile'),
    path('profile/change_password', change_password, name = 'change_password'),
    path('profile/profile_update/', profile_update, name = 'profile_update'),
    path('create_user/', register, name='create_user'),
    path('edit_user/<int:pk>', edit_user, name = 'edit_user'),
    path('delete_user/<int:pk>', delete_user, name = 'delete_user'),
    path('patch_user/<int:pk>', patch_user, name = 'patch_user'),# patch - не большое обновление данных пользователя
    path('index/', users, name = 'users'),
    path('change_password/<int:pk>', change_password, name = 'change_password'),
]

journal/student/models.py
from django.db import models



# Create your models here.

journal/student/views.py
from django.shortcuts import render

def schedule(request):
    return render(request, 'schedule.html')

# Create your views here.

journal/student/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Мой сайт{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Bootstrap Select CSS -->
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">

    <!-- Ваши стили -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Иконка сайта -->
    <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}">
</head>

<body>

    <!-- SIDEBAR -->
    <div class="sidebar">
        <a class="navbar-brand m-0 p-0 d-flex justify-content-center align-items-center" href="">
            <img src="{% static 'images/icon.png' %}" alt="icon" class="navbar-logo">
        </a>
        <a href="{% url 'users:profile' %}">
            <i class="bi bi-person-circle me-2"></i> Профиль
        </a>

        {% if user.is_superuser %}
        <a href="{% url 'users:users' %}">
            <i class="bi bi-plus-lg me-2"></i> Все пользователи
        </a>
        {% endif %}

        <a href="{% url 'administrator:halls' %}" class="sidebar-link trainer-link">
            <i class="bi bi-building me-2"></i>
            <span>Залы</span>
        </a>

        <a href="{% url 'administrator:coaches' %}" class="sidebar-link trainer-link">
            <i class="bi bi-person-badge-fill me-2 text-success"></i>
            <span>Тренеры</span>
        </a>

        <a href="{% url 'administrator:students' %}" class="sidebar-link athlete-link">
            <i class="bi bi-person-check-fill me-2 text-warning"></i>
            <span>Спортсмены</span>
        </a>

        {% if user.is_superuser %}
        <a href="{% url 'administrator:group' %}">
            <i class="bi bi-people me-2"></i> Группы
        </a>
        {% endif %}

        <a href="{% url 'administrator:schedule' %}">
            <i class="bi bi-grid me-2"></i> Расписание
        </a>

        <a href="{% url 'administrator:periods' %}">
            <i class="bi bi-calendar me-2"></i> Периоды
        </a>

        <a href="#">
            <i class="bi-trophy me-2"></i> График соренований
        </a>

        <a href="#">
            <i class='bi-journal-check me-2'></i> КПИ
        </a>

        <a href="#">
            <i class="bi-book-half me-2"></i> Домашнее задание
        </a>

        <a href="#">
            <i class="bi bi-envelope me-2"></i> Сообщения
        </a>

        <a href="{% url 'users:log_out' %}">
            <i class="bi bi-box-arrow-right me-2"></i> Выйти
        </a>
    </div>

    <!-- CONTENT -->
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block script %}

    {% endblock %}
</body>

</html>